---
title: "sample codes"
author: "Nicolas Min"
date: "4/7/2022"
output: pdf_document
---

```{r}
library(dplyr)
library(ggplot2)
library(plm)
library(lmtest)
library(maps) 
library(here)
library(stringr)
```

# Math inside RMD
```{r}
# https://rpruim.github.io/s341/S19/from-class/MathinRmd.html
```

# Linear Regression with Fixed Effects
$$Output_i =\alpha + \beta_1emp + \beta_2wage + \beta_3capital+ \sum_{j=1977}^{1984}\gamma_j1(sector_i = j)  + \sum_{c=2}^{9}\delta_c1(sector_i = c) + \epsilon_i$$
```{r}
data("EmplUK", package="plm")

#https://www.youtube.com/watch?v=ghNSChAymF4
#using lm()
summary(lm(output ~ emp + wage + capital +factor(year)+ factor(sector), data=EmplUK))
#using plm()
summary(plm(output ~ emp + wage + capital +factor(year), index=c("sector") , model="within", data=EmplUK))

#https://bookdown.org/ccolonescu/RPoE4/panel-data-models.html
#using plm() but use robust SE
plm_model <- plm(output ~ emp + wage + capital +factor(sector), index=c("year") , model="within", data=EmplUK)
coeftest(plm_model, vcov=vcovHC(plm_model, type="HC1",cluster="group"))
```

# MAP
```{r}
#read datasets in R
MainStates <- map_data("state") #state location (grouped)
AllCounty <- map_data("county") #county location (grouped)
MainCities <- filter(us.cities, long>=-130) #population by city

# read 3rd party 'state' population data
StatePopulation <- read.csv("https://raw.githubusercontent.com/ds4stats/r-tutorials/master/intro-maps/data/StatePopulation.csv", as.is = TRUE)
MergedStates <- inner_join(MainStates, StatePopulation, by = "region")

ggplot(data = MergedStates) + 
  geom_polygon(aes(x = long,y = lat,group = group,fill = population / 1000000), color = "white",size = 0.2)+
  theme_minimal()+
  ggtitle("US Population (state level)")

ggplot() + 
  geom_polygon( data=AllCounty, aes(x=long, y=lat, group=group),
                         color="white", fill="lightblue", size = .1 ) +
  geom_polygon( data=MainStates, aes(x=long, y=lat, group=group),
                color="black", fill="darkblue",  size = 1, alpha = .3)+
  geom_point(data=MainCities, aes(x=long, y=lat, size = pop/1000000), color = "gold", alpha = .5)+
  theme_minimal()+
  ggtitle("US Population")
ggsave("../plot/sample plot.png")

ggplot() + 
  geom_polygon( data=AllCounty[AllCounty$region == "california",], aes(x=long, y=lat, group=group),
                         color="darkblue", fill="lightblue", size = .1 ) +
  geom_polygon( data=MainStates[MainStates$region =="california",], aes(x=long, y=lat, group=group),
                color="black", fill="lightblue",  size = 1, alpha = .3) +
  geom_point(data=MainCities[MainCities$country.etc == "CA",], aes(x=long, y=lat, size = pop/1000000), color = "gold", alpha = .5) +
  theme_minimal() +
  ggtitle("California Population")
ggsave("../plot/sample plot2.png")
```

# Heatmap
```{r}

```

```{r}
#ML
#https://www.geeksforgeeks.org/7-best-r-packages-for-machine-learning/
  
```

