---
title: "Other variables"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(plm)
library(lmtest)
library(maps) 
library(here)
library(stringr)
library("randomForest")
install.packages("ggcorrplot")
library(ggcorrplot)
```

#Selecting
```{r}
cleaned_data <- read.csv("../data/diabetic_data_prelim_cleaned.csv")
medicine <- cleaned_data[,25:46]
corrout <- select(medicine, -c(examide, glimepiride.pioglitazone, citoglipton))
out<-data.matrix(corrout)
corrout <- cor(out)
```
Removing examide, glimepiride. pio and cytoglipton

#Manipulation
Also seek to remove top 10% of correlation.
```{r}
ggcorrplot(corrout, method = c("square", "circle"), type = c("full",
  "lower", "upper"), ggtheme = ggplot2::theme_minimal, title = "",
  show.legend = TRUE, legend.title = "Corr", show.diag = FALSE,
  colors = c("blue", "white", "red"), outline.color = "gray",
  hc.order = FALSE, hc.method = "complete", lab = FALSE,
  lab_col = "black", lab_size = 4, p.mat = NULL, sig.level = 0.05,
  insig = c("pch", "blank"), pch = 4, pch.col = "black",
  pch.cex = 5, tl.cex = 12, tl.col = "black", tl.srt = 45,
  digits = 2)
sort(corrout)
```


